spring:
  datasource:
    url: ${DB_URL:jdbc:mysql://localhost:3306/bd_cinema}
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:silva2236}
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: ${JPA_SHOW_SQL:false}
    properties:
      hibernate:
        format_sql: true
  sql:
    init:
      mode: never
  jackson:
    serialization:
      FAIL_ON_EMPTY_BEANS: false
  web:
    resources:
      add-mappings: false

logging:
  level:
    root: INFO
    br.com.sgc: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"

app:
  jwt:
    secret: ${JWT_SECRET:sua_secret_key_muito_segura_com_mais_de_32_caracteres_aqui}
    expiration: ${JWT_EXPIRATION:3600000}

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
  api-docs:
    path: /v3/api-docs
